#!/usr/bin/env python3
"""quest_zmq_publisher.py — Meta Quest → SONIC ZMQ Protocol v3 bridge.

Runs a browser-based WebXR server (via vuer / OpenTeleVision) so that the
Quest's built-in browser can stream head and hand poses without any APK build
or sideloading. Converts the poses to SONIC's ZMQ Protocol v3 format and
publishes them on port 5556 at 50 Hz, making this script the Quest equivalent
of pico_manager_thread_server.py.

Usage
-----
    # One-time install:
    bash install_scripts/install_quest.sh

    # Terminal 1 — MuJoCo sim:
    python gear_sonic/scripts/run_sim_loop.py

    # Terminal 2 — C++ deployment:
    ./deploy.sh sim --input-type zmq --zmq-host localhost --zmq-port 5556

    # Terminal 3 — this script:
    source .venv_teleop/bin/activate
    python gear_sonic/scripts/quest_zmq_publisher.py

    Open the printed URL in the Meta Quest Browser, then activate VR_3PT
    in the deployment (Left Stick click after pressing ] to start the policy).

Options
-------
--ngrok          Use ngrok tunnel (default: True). Set False for same-WiFi,
                 requires cert.pem / key.pem in the repo root (generated by
                 install_quest.sh).
--cert           Path to TLS cert PEM (default: ./cert.pem).
--key            Path to TLS key PEM  (default: ./key.pem).
--zmq-port       ZMQ PUB port (default: 5556).
--zmq-topic      ZMQ topic string (default: pose).
--hz             Publishing rate in Hz (default: 50).
--connect-wait   Seconds to wait after starting vuer before publishing
                 (default: 8).
"""

import argparse
import json
import multiprocessing
import socket
import time
import urllib.request
from multiprocessing import shared_memory
from pathlib import Path

import msgpack
import numpy as np
import zmq
from scipy.spatial.transform import Rotation as R

from gear_sonic.utils.opentelevision import OpenTeleVision
from gear_sonic.utils.teleop.zmq.zmq_planner_sender import build_command_message, build_planner_message

# Repo root = two levels up from this script (gear_sonic/scripts/quest_zmq_publisher.py)
_REPO_ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Coordinate frame conversion
# ---------------------------------------------------------------------------
# vuer (WebXR) uses a Y-up right-handed frame:
#   X = right, Y = up, Z = toward viewer (out of screen)
#
# SONIC / SMPL uses a Z-up right-handed frame:
#   X = forward, Y = left, Z = up
#
# This matrix (from LW-BenchHub lw_benchhub/core/devices/vr/consts.py) converts
# a homogeneous pose from WebXR Y-up to SONIC Z-up.
_GRD_YUP2GRD_ZUP = np.array([
    [ 0,  0, -1,  0],
    [-1,  0,  0,  0],
    [ 0,  1,  0,  0],
    [ 0,  0,  0,  1],
], dtype=np.float64)


def _has_valid_rotation(mat4x4: np.ndarray) -> bool:
    """Return True if mat4x4's upper-left 3x3 is a valid rotation matrix (det ≈ 1).

    An uninitialised shared-memory block is all zeros (det = 0).
    A valid SE(3) pose always has det(R) = +1.
    Using |det - 1| < 0.1 is robust to small floating-point noise.
    """
    return abs(np.linalg.det(mat4x4[:3, :3]) - 1.0) < 0.1


def _mat2pos_quat(mat4x4: np.ndarray):
    """Extract position and quaternion (w, x, y, z) from a 4x4 matrix."""
    pos = mat4x4[:3, 3].copy()
    xyzw = R.from_matrix(mat4x4[:3, :3]).as_quat()   # scipy: x, y, z, w
    wxyz = np.array([xyzw[3], xyzw[0], xyzw[1], xyzw[2]], dtype=np.float64)
    return pos, wxyz


def _encode_ndarray(obj):
    """msgpack custom encoder for numpy arrays (replicates PICO server encoder)."""
    if isinstance(obj, np.ndarray):
        return msgpack.ExtType(1, obj.astype(np.float32).tobytes())
    raise TypeError(f"Unknown type: {type(obj)}")


def _parse_args():
    p = argparse.ArgumentParser(description="Meta Quest → SONIC ZMQ bridge")
    p.add_argument("--ngrok", action=argparse.BooleanOptionalAction, default=True,
                   help="Use ngrok tunnel (default: True). Disable for same-WiFi + cert.")
    p.add_argument("--cert", default=str(_REPO_ROOT / "cert.pem"), help="TLS cert PEM path.")
    p.add_argument("--key",  default=str(_REPO_ROOT / "key.pem"),  help="TLS key PEM path.")
    p.add_argument("--zmq-port",      type=int,   default=5556,   help="ZMQ PUB port.")
    p.add_argument("--zmq-topic",     type=str,   default="pose", help="ZMQ topic.")
    p.add_argument("--hz",            type=float, default=50.0,   help="Publish rate Hz.")
    p.add_argument("--connect-wait",  type=float, default=8.0,
                   help="Seconds to wait for Quest to connect after vuer starts.")
    p.add_argument("--debug", action="store_true",
                   help="Print raw matrix determinants every second to diagnose connection issues.")
    p.add_argument("--quest-cam", action="store_true", default=False,
                   help="Stream MuJoCo head_camera frames to Quest. "
                        "Requires run_sim_loop.py --quest-cam to be running.")
    return p.parse_args()


def main():
    args = _parse_args()

    if not args.ngrok:
        for fpath in (args.cert, args.key):
            if not Path(fpath).exists():
                raise FileNotFoundError(
                    f"TLS file not found: {fpath}\n"
                    "Generate it with:\n"
                    "  openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem "
                    "-days 365 -nodes -subj '/CN=localhost'"
                )

    # ------------------------------------------------------------------
    # Shared memory for image streaming.
    # --quest-cam: attach to the named block "quest_head_cam" that
    #   run_sim_loop.py creates and fills with head_camera frames.
    # default: create an anonymous block (never written — blank image).
    # ------------------------------------------------------------------
    _QUEST_CAM_SHM_NAME = "quest_head_cam"
    img_shape = (480, 640, 3)
    if args.quest_cam:
        # Wait for the sim to create the named block (up to 30 s).
        shm = None
        print("[quest_zmq_publisher] --quest-cam: waiting for sim to create 'quest_head_cam' shm …")
        deadline = time.time() + 30
        while time.time() < deadline:
            try:
                shm = shared_memory.SharedMemory(name=_QUEST_CAM_SHM_NAME)
                print(f"[quest_zmq_publisher] Opened 'quest_head_cam' shm ({img_shape[0]}x{img_shape[1]})")
                break
            except FileNotFoundError:
                time.sleep(0.5)
        if shm is None:
            raise RuntimeError(
                "Timed out waiting for 'quest_head_cam' shared memory. "
                "Make sure run_sim_loop.py is running with --quest-cam."
            )
    else:
        shm = shared_memory.SharedMemory(create=True, size=int(np.prod(img_shape)))

    # ------------------------------------------------------------------
    # Start vuer WebXR server in a daemon subprocess.
    # ngrok=True  — vuer prints a public ngrok HTTPS URL; works on any network.
    # ngrok=False — vuer binds to 0.0.0.0 with the local cert/key; Quest and
    #               workstation must be on the same WiFi network.
    # ------------------------------------------------------------------
    tv = OpenTeleVision(
        img_shape=img_shape[:2],
        shm_name=shm.name,
        device_type="hand",        # Quest hand tracking (controller mode freezes Quest browser)
        ngrok=args.ngrok,
        cert_file=args.cert,
        key_file=args.key,
    )

    print(f"[quest_zmq_publisher] vuer WebXR server started.")
    if args.ngrok:
        # vuer prints the ngrok URL to the subprocess log. Scan it for an https://...ngrok URL.
        import re
        vuer_url = None
        deadline = time.time() + 20
        print("[quest_zmq_publisher] Waiting for ngrok tunnel URL …", flush=True)
        while time.time() < deadline:
            time.sleep(1)
            try:
                with open("/tmp/opentelevision_subprocess.log") as f:
                    for line in f:
                        m = re.search(r'(https://[^\s]*ngrok[^\s]*)', line)
                        if m:
                            vuer_url = m.group(1)
            except FileNotFoundError:
                pass
            if vuer_url:
                break
        if vuer_url:
            print(f"[quest_zmq_publisher] Open in Quest browser: {vuer_url}")
        else:
            print("[quest_zmq_publisher] Could not find ngrok URL — check /tmp/opentelevision_subprocess.log")
    else:
        # Detect the local IP that would be reachable from the Quest.
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(("8.8.8.8", 80))
            local_ip = s.getsockname()[0]
            s.close()
        except Exception:
            local_ip = "<workstation-ip>"
        print(f"[quest_zmq_publisher] Same-WiFi mode — open https://{local_ip}:8012 on Quest.")
    if not args.ngrok:
        print(f"[quest_zmq_publisher] Waiting {args.connect_wait:.0f} s for Quest browser to connect …")
        time.sleep(args.connect_wait)

    # ------------------------------------------------------------------
    # ZMQ publisher — SONIC deploy.sh subscribes here.
    # ------------------------------------------------------------------
    ctx = zmq.Context()
    pub = ctx.socket(zmq.PUB)
    pub.bind(f"tcp://*:{args.zmq_port}")
    topic = args.zmq_topic.encode()

    def _send_command(start: bool, stop: bool, planner: bool):
        # build_command_message returns: b"command" + 1280-byte JSON header + binary payload
        pub.send(build_command_message(start=start, stop=stop, planner=planner))

    def _command_input_thread():
        """Background thread: read keypresses and send ZMQ command messages."""
        import sys, tty, termios
        fd = sys.stdin.fileno()
        old = termios.tcgetattr(fd)
        try:
            tty.setraw(fd)
            while True:
                ch = sys.stdin.read(1)
                if ch in (']', 's', 'S'):
                    _send_command(start=True, stop=False, planner=True)
                    print("\r[quest_zmq_publisher] START sent → robot should stand up", flush=True)
                elif ch in ('o', 'O'):
                    _send_command(start=False, stop=True, planner=False)
                    print("\r[quest_zmq_publisher] STOP sent → emergency stop", flush=True)
                elif ch in ('p', 'P'):
                    _send_command(start=False, stop=False, planner=True)
                    print("\r[quest_zmq_publisher] PLANNER mode sent", flush=True)
                elif ch == '\x03':  # Ctrl-C
                    break
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old)

    import threading
    _t = threading.Thread(target=_command_input_thread, daemon=True)
    _t.start()

    dt = 1.0 / args.hz
    frame_idx = 0

    print(f"[quest_zmq_publisher] Publishing ZMQ Protocol v3 on port {args.zmq_port} "
          f"at {args.hz:.0f} Hz (topic={args.zmq_topic}) …")
    print("[quest_zmq_publisher] Move head / hands on the Quest to stream poses.")
    print("[quest_zmq_publisher] Keys: ] or S = START  |  O = STOP  |  P = PLANNER  |  V = VR_3PT")

    waiting_logged = False
    debug_t = time.perf_counter()
    while True:
        t0 = time.perf_counter()

        # Read 4x4 homogeneous pose matrices from vuer (column-major / WebXR Y-up)
        head_raw = tv.head_matrix
        lh_raw   = tv.left_hand
        rh_raw   = tv.right_hand

        if args.debug and (t0 - debug_t) >= 1.0:
            debug_t = t0
            print(f"[debug] subprocess pid={tv.process.pid}  alive={tv.process.is_alive()}  exitcode={tv.process.exitcode}")
            print(f"[debug] head det={np.linalg.det(head_raw[:3,:3]):.3f}  "
                  f"lh det={np.linalg.det(lh_raw[:3,:3]):.3f}  "
                  f"rh det={np.linalg.det(rh_raw[:3,:3]):.3f}")
            print(f"[debug] head[0]={head_raw[0].tolist()}")
            print(f"[debug] lh[0]  ={lh_raw[0].tolist()}")

        # Guard: wait until at least one matrix has a valid rotation (det ≈ 1).
        #
        # Why not np.allclose(head_raw, 0)?
        #   on_cam_move (CAMERA_MOVE) only fires when the headset physically moves.
        #   on_hand_move (HAND_MOVE) fires independently as soon as hands are tracked.
        #   Either event arriving means the XR session is live — accept either one.
        #   A zero rotation matrix has det = 0; a valid SE(3) pose has det(R) = +1.
        head_valid = _has_valid_rotation(head_raw)
        lh_valid   = _has_valid_rotation(lh_raw)
        rh_valid   = _has_valid_rotation(rh_raw)

        if not (head_valid or lh_valid or rh_valid):
            if not waiting_logged:
                print("[quest_zmq_publisher] Waiting for XR session data "
                      "(open the URL in the Quest browser, enter VR mode, "
                      "then move your head or hands) …")
                waiting_logged = True
            time.sleep(dt)
            continue
        waiting_logged = False

        # Use identity pose for any tracker not yet reporting valid data.
        # This is safe in VR_3PT: SONIC calibrates wrists on entry, so a
        # brief identity pose before hands are tracked causes no harm.
        if not head_valid:
            head_raw = np.eye(4)
        if not lh_valid:
            lh_raw = np.eye(4)
        if not rh_valid:
            rh_raw = np.eye(4)

        head_mat = _GRD_YUP2GRD_ZUP @ head_raw
        lh_mat   = _GRD_YUP2GRD_ZUP @ lh_raw
        rh_mat   = _GRD_YUP2GRD_ZUP @ rh_raw

        head_pos, head_quat = _mat2pos_quat(head_mat)
        lh_pos,   lh_quat   = _mat2pos_quat(lh_mat)
        rh_pos,   rh_quat   = _mat2pos_quat(rh_mat)

        # Send planner message with VR_3PT tracking data embedded.
        # The ZMQManager reads vr_position / vr_orientation from the planner
        # topic and uses them to drive the robot's upper body in VR_3PT mode.
        # vr_position:    flat f32[9]  = [head_xyz, lh_xyz, rh_xyz]
        # vr_orientation: flat f32[12] = [head_wxyz, lh_wxyz, rh_wxyz]
        vr_pos = np.concatenate([head_pos, lh_pos, rh_pos]).astype(np.float32)
        vr_ori = np.concatenate([head_quat, lh_quat, rh_quat]).astype(np.float32)
        pub.send(build_planner_message(
            mode=0,                     # Idle — no locomotion by default
            movement=[0.0, 0.0, 0.0],
            facing=[1.0, 0.0, 0.0],
            vr_3pt_position=vr_pos.tolist(),
            vr_3pt_orientation=vr_ori.tolist(),
        ))
        frame_idx += 1

        elapsed = time.perf_counter() - t0
        time.sleep(max(0.0, dt - elapsed))


if __name__ == "__main__":
    # spawn is required because OpenTeleVision launches a child Process and
    # vuer uses asyncio internally — fork can leave asyncio in a bad state.
    multiprocessing.set_start_method("spawn", force=True)
    main()
