#!/usr/bin/env python3
"""quest_zmq_publisher.py — Meta Quest → SONIC ZMQ Protocol v3 bridge.

Runs a browser-based WebXR server (via vuer / OpenTeleVision) so that the
Quest's built-in browser can stream head and hand poses without any APK build
or sideloading. Converts the poses to SONIC's ZMQ Protocol v3 format and
publishes them on port 5556 at 50 Hz, making this script the Quest equivalent
of pico_manager_thread_server.py.

Usage
-----
    # One-time install:
    bash install_scripts/install_quest.sh

    # Terminal 1 — MuJoCo sim:
    python gear_sonic/scripts/run_sim_loop.py

    # Terminal 2 — C++ deployment:
    ./deploy.sh sim --input-type zmq --zmq-host localhost --zmq-port 5556

    # Terminal 3 — this script:
    source .venv_teleop/bin/activate
    python gear_sonic/scripts/quest_zmq_publisher.py

    Open the printed URL in the Meta Quest Browser, then activate VR_3PT
    in the deployment (Left Stick click after pressing ] to start the policy).

Options
-------
--ngrok          Use ngrok tunnel (default: True). Set False for same-WiFi,
                 requires cert.pem / key.pem in the repo root (generated by
                 install_quest.sh).
--cert           Path to TLS cert PEM (default: ./cert.pem).
--key            Path to TLS key PEM  (default: ./key.pem).
--zmq-port       ZMQ PUB port (default: 5556).
--zmq-topic      ZMQ topic string (default: pose).
--hz             Publishing rate in Hz (default: 50).
--connect-wait   Seconds to wait after starting vuer before publishing
                 (default: 8).
"""

import argparse
import multiprocessing
import time
from multiprocessing import shared_memory

import msgpack
import numpy as np
import zmq
from scipy.spatial.transform import Rotation as R

from gear_sonic.utils.opentelevision import OpenTeleVision

# ---------------------------------------------------------------------------
# Coordinate frame conversion
# ---------------------------------------------------------------------------
# vuer (WebXR) uses a Y-up right-handed frame:
#   X = right, Y = up, Z = toward viewer (out of screen)
#
# SONIC / SMPL uses a Z-up right-handed frame:
#   X = forward, Y = left, Z = up
#
# This matrix (from LW-BenchHub lw_benchhub/core/devices/vr/consts.py) converts
# a homogeneous pose from WebXR Y-up to SONIC Z-up.
_GRD_YUP2GRD_ZUP = np.array([
    [ 0,  0, -1,  0],
    [-1,  0,  0,  0],
    [ 0,  1,  0,  0],
    [ 0,  0,  0,  1],
], dtype=np.float64)


def _mat2pos_quat(mat4x4: np.ndarray):
    """Extract position and quaternion (w, x, y, z) from a 4x4 matrix."""
    pos = mat4x4[:3, 3].copy()
    xyzw = R.from_matrix(mat4x4[:3, :3]).as_quat()   # scipy: x, y, z, w
    wxyz = np.array([xyzw[3], xyzw[0], xyzw[1], xyzw[2]], dtype=np.float64)
    return pos, wxyz


def _encode_ndarray(obj):
    """msgpack custom encoder for numpy arrays (replicates PICO server encoder)."""
    if isinstance(obj, np.ndarray):
        return msgpack.ExtType(1, obj.astype(np.float32).tobytes())
    raise TypeError(f"Unknown type: {type(obj)}")


def _parse_args():
    p = argparse.ArgumentParser(description="Meta Quest → SONIC ZMQ bridge")
    p.add_argument("--ngrok", action=argparse.BooleanOptionalAction, default=True,
                   help="Use ngrok tunnel (default: True). Disable for same-WiFi + cert.")
    p.add_argument("--cert", default="./cert.pem", help="TLS cert PEM path.")
    p.add_argument("--key",  default="./key.pem",  help="TLS key PEM path.")
    p.add_argument("--zmq-port",      type=int,   default=5556,   help="ZMQ PUB port.")
    p.add_argument("--zmq-topic",     type=str,   default="pose", help="ZMQ topic.")
    p.add_argument("--hz",            type=float, default=50.0,   help="Publish rate Hz.")
    p.add_argument("--connect-wait",  type=float, default=8.0,
                   help="Seconds to wait for Quest to connect after vuer starts.")
    return p.parse_args()


def main():
    args = _parse_args()

    # ------------------------------------------------------------------
    # Shared memory stub required by OpenTeleVision even when image
    # streaming is unused (stream_mode="image" is the default; the image
    # array is simply never written by quest_zmq_publisher).
    # ------------------------------------------------------------------
    img_shape = (480, 640, 3)
    shm = shared_memory.SharedMemory(create=True, size=int(np.prod(img_shape)))

    # ------------------------------------------------------------------
    # Start vuer WebXR server in a daemon subprocess.
    # ngrok=True  — vuer prints a public ngrok HTTPS URL; works on any network.
    # ngrok=False — vuer binds to 0.0.0.0 with the local cert/key; Quest and
    #               workstation must be on the same WiFi network.
    # ------------------------------------------------------------------
    tv = OpenTeleVision(
        img_shape=img_shape[:2],
        shm_name=shm.name,
        device_type="hand",        # Quest hand tracking (controller mode freezes Quest browser)
        ngrok=args.ngrok,
        cert_file=args.cert,
        key_file=args.key,
    )

    print(f"[quest_zmq_publisher] vuer WebXR server started.")
    if args.ngrok:
        print("[quest_zmq_publisher] ngrok tunnel active — check above for the public URL.")
    else:
        print("[quest_zmq_publisher] Same-WiFi mode — open https://<workstation-ip>:8012 on Quest.")
    print(f"[quest_zmq_publisher] Waiting {args.connect_wait:.0f} s for Quest browser to connect …")
    time.sleep(args.connect_wait)

    # ------------------------------------------------------------------
    # ZMQ publisher — SONIC deploy.sh subscribes here.
    # ------------------------------------------------------------------
    ctx = zmq.Context()
    pub = ctx.socket(zmq.PUB)
    pub.bind(f"tcp://*:{args.zmq_port}")
    topic = args.zmq_topic.encode()

    dt = 1.0 / args.hz
    frame_idx = 0

    print(f"[quest_zmq_publisher] Publishing ZMQ Protocol v3 on port {args.zmq_port} "
          f"at {args.hz:.0f} Hz (topic={args.zmq_topic}) …")
    print("[quest_zmq_publisher] Move head / hands on the Quest to stream poses.")

    waiting_logged = False
    while True:
        t0 = time.perf_counter()

        # Read 4x4 homogeneous pose matrices from vuer (column-major / WebXR Y-up)
        head_raw = tv.head_matrix
        lh_raw   = tv.left_hand
        rh_raw   = tv.right_hand

        # Before a Quest browser connects, all matrices are zeros.
        # Skip until at least the head matrix carries a valid rotation.
        if np.allclose(head_raw, 0):
            if not waiting_logged:
                print("[quest_zmq_publisher] Waiting for Quest to connect (matrices still zero) …")
                waiting_logged = True
            time.sleep(dt)
            continue
        waiting_logged = False

        head_mat = _GRD_YUP2GRD_ZUP @ head_raw
        lh_mat   = _GRD_YUP2GRD_ZUP @ lh_raw
        rh_mat   = _GRD_YUP2GRD_ZUP @ rh_raw

        head_pos, head_quat = _mat2pos_quat(head_mat)
        lh_pos,   lh_quat   = _mat2pos_quat(lh_mat)
        rh_pos,   rh_quat   = _mat2pos_quat(rh_mat)

        # Protocol v3 message.
        # Only vr_position and vr_orientation are consumed by VR_3PT mode.
        # All lower-body fields are zeroed; the planner drives legs from joystick.
        msg = {
            "vr_position":    np.array([[head_pos, lh_pos, rh_pos]]),    # [1, 3, 3]
            "vr_orientation": np.array([[head_quat, lh_quat, rh_quat]]), # [1, 3, 4]  w,x,y,z
            "body_quat":      head_quat.reshape(1, 4),                   # [1, 4]
            "frame_index":    np.array([frame_idx]),
            # Unused in VR_3PT — zeroed to satisfy the protocol schema
            "joint_pos":   np.zeros((1, 29)),
            "joint_vel":   np.zeros((1, 29)),
            "smpl_joints": np.zeros((1, 24, 3)),
            "smpl_pose":   np.zeros((1, 21, 3)),
        }
        pub.send_multipart([topic, msgpack.packb(msg, default=_encode_ndarray)])
        frame_idx += 1

        elapsed = time.perf_counter() - t0
        time.sleep(max(0.0, dt - elapsed))


if __name__ == "__main__":
    # spawn is required because OpenTeleVision launches a child Process and
    # vuer uses asyncio internally — fork can leave asyncio in a bad state.
    multiprocessing.set_start_method("spawn", force=True)
    main()
